name:                hml-prototype
version:             0.1.0.0
github:              "githubuser/hml-prototype"

extra-source-files:
- readme.txt

description:         Please see the README on GitHub at <https://github.com/githubuser/hml-prototype#readme>

dependencies:
- base >= 4.8 && < 5
- parsec >= 3.1
- containers >= 0.5

executables:
  hml-prototype:
    main:                Main.hs
    source-dirs:         src
